### ISSUE TITLE
Attempt extraction of build vars from zips when adding

### ISSUE THREAD

**Issue by patcon** [xdarklight/cm-update-server#2]
Not sure if this is too messy for you or not properly cross-platform, but would be great to make a best effort to extract possible arg values from the zips when adding

```
unzip -p cm-11-grouper.snapshot-M12.zip system/build.prop | grep ro.build
```

Thinking we can get these:
- incrementalid `ro.build.version.incremental`
- device `ro.product.device`
- timestamp `ro.build.date.utc`
- sdk ver `ro.build.version.sdk`
- channel? `ro.cm.releasetype` (cm-only?)
- md5sum (generate)

(flags would still override)

But maybe it's not worth it. I'll see if I feel like it when I get using it :)

**Comment by xdarklight** [comment]
Right now the build-cm script (https://github.com/xdarklight/build-cm-script/blob/master/build-cm.sh#L172) is doing this.
But I guess instead of relying on the system to provide "unzip" we should do it from within NodeJS. Seems to be quite easy with https://www.npmjs.com/package/adm-zip

Please note that incrementals cannot be parsed (that easy) on the NodeJS side because they only have a "system/build.prop.p" (not a plaintext file).

**Comment by patcon** [comment]
Ah gotcha. Actually, I hadn't looked at that repo yet, so thanks

**Comment by zefie** [comment]
I know this is old, but this is what I do for the time being:

http://pastebin.com/QE7evDjP

Using this script, in the scenario that it was named "addfile.sh" in the cm-update-server directory, and you had your rom at:
_data/files/lineageos-13.0-gtelwifiue/lineage-13.0_j60_20170324_NIGHTLY-gtelwifiue.zip_

You could:
`./addfile.sh data/files/lineageos-13.0-gtelwifiue/lineage-13.0_j60_20170324_NIGHTLY-gtelwifiue.zip`
OR
`./addfile.sh lineage-13.0_j60_20170324_NIGHTLY-gtelwifiue.zip`
OR
`./addfile.sh lineage-13.0_j60`

to accomplish the same thing.

**Comment by xdarklight** [comment]
I am not maintaining this project anymore so I'm closing this.
