### ISSUE TITLE
Resource not Found

### ISSUE THREAD

**Issue by imrasalghul** [xdarklight/cm-update-server#5]
This may be a n00b-ish question, but when I'm running the server, where exactly does the ROM files go? I attempted to put them in ./data/subdirectory, ./website/build/subdirectory, and even in the root of the directory and I always get a resource not found error message. @xdarklight

**Comment by imrasalghul** [comment]
Ah, figured it out, thanks!

**Comment by imrasalghul** [comment]
Wait, no I didn't.

**Comment by xdarklight** [comment]
I haven't tried to deliver the ROM files through cm-updater yet.
My setups always included a reverse-proxy in front of cm-update-server which takes care of serving the download files (because in my case it's not only one server but a small "CDN" which delivers the ROM files).

Nevertheless, I'll look into this later this week - I'm sure that it has to be possible.

**Comment by xdarklight** [comment]
I have pushed a comment in config/default.js:
mkdir -p ./data/files/downloads/
Put all zip files in there, then you'll be able to reach them through localhost:3000/downloads/nameofyour.zip

**Comment by imrasalghul** [comment]
Thank you! @xdarklight
